version: "3.7"

services:

  notification-nest:
    container_name: notification-nest
    image: notification-nest
    build:
      context: docker/nest
    ports:
      - 3000:3000
    volumes:
      - ..:/app
    networks:
      - notification
    restart: unless-stopped


  notification-db:
    container_name: notification-db
    build:
      context: docker/pgsql
    ports:
      - ${POSTGRES_IP:-0.0.0.0}:${DB_PORT:-5432}:5432
    volumes:
      - notification-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-notify-demo}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    networks:
      - notification
    restart: unless-stopped

  notification-mail:
    container_name: notification-mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAIL_PORT:-1025}:1025
      - ${MAIL_WEB_PORT:-8025}:8025
    networks:
      - notification
    restart: unless-stopped


volumes:
  notification-db:
    name: notification-db
    driver: local


networks:
  notification:
    name: notification
    driver: bridge
