version: "3.7"

services:

  notification-nest:
    container_name: notification-nest
    image: notification-nest
    build:
      context: .
      dockerfile: ./nest/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ..:/usr/src/app
    networks:
      - notification

  notification-db:
    container_name: notification-db
    build:
      context: pgsql
    restart: always
    ports:
      - ${DC_POSTGRES_IP:-0.0.0.0}:${DC_POSTGRES_PORT:-5432}:5432
    volumes:
      - notification-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DC_DATABASE:-notification}
      POSTGRES_PASSWORD: ${DC_POSTGRES_PASS:-postgres}
    networks:
      - notification

  notification-mail:
    container_name: notification-mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - ${DC_MAIL_PORT:-1025}:1025
      - ${DC_MAIL_WEB_PORT:-58025}:8025
    networks:
      - notification


volumes:
  notification-db:
    name: notification-db
    driver: local


networks:
  notification:
    name: notification
    driver: bridge
